name: Deploy to Azure VM

on:
  push:
    branches:
      - LukePickard  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22  # Adjust the port if needed
          script: |
            cd /home/itintern/project_repo/RPG-Backend
            git pull origin LukePickard
            npm install
            npm run start


